# Configuration Port
server:
  port: 8081
  servlet:
    session:
      timeout: 1800


spring:
  # Configuration PostgreSQL
  datasource:
    url: jdbc:postgresql://localhost:5432/mygg
    username: orderuser
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

# Configuration Thymeleaf
  thymeleaf:
    prefix: classpath:/templates
    suffix: .html
    cache: false

  # Configuration Devtools
  devtools:
    livereload:
      enabled: true
    restart:
      enable: false

logging:
  level:
    org.springframework.security: DEBUG

